### ISSUE TITLE
Turning on Gnome-Feeder results in turning "ALL_trading_enable = true" to "ALL_trading_enable = false|

### ISSUE THREAD

**Issue by Matrond** [CryptoGnome/Gnome-Feeder#1]
I'm having an issue where when I turn on Gnome-Feeder (several minutes after turning on PT), it changes  "ALL_trading_enabled = true" to "ALL_trading_enabled = false" when the market is 'Boring'. Below are the settings that are overwritten in my 'PAIRS.properties' in PT once I open Gnome-Feeder:

Does anyone know how to fix this issue?

# ---------------USING 03-boring. WRITTEN ON Wednesday, January 10, 2018 12:57:18 PM UTC ---------------

MARKET = BTC
ALL_trading_enabled = false

ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.2
ALL_sell_strategy = GAIN
ALL_sell_value = 0.75
ALL_trailing_profit = 0.3
ALL_trailing_buy = 0.3
ALL_DCA_enabled = -2
ALL_min_buy_volume = 50
ALL_min_buy_price = 0.00005
ALL_min_profit = 0.5
ALL_enabled_pairs = ALL
ALL_max_buy_spread = 0.5
ALL_panic_sell_enabled = false
ALL_sell_only_mode = false
ALL_max_cost = 0
ALL_max_cost_percentage = 3
ALL_min_buy_balance = 0
ALL_min_buy_balance_percentage = 40
ALL_max_trading_pairs = 15

---

**Comment by Q-Rush** [comment]
its not an issue AFAIK. It will always set it to false and set COINPAIR_trading_enabled to false or true to allow excluded pairs.
So for example i exclude some pairs that i want to hold. those are set to false automatically.

**Comment by CryptoGnome** [comment]
Read the WIKI!
