### ISSUE TITLE
Different settings 

### ISSUE THREAD

**Issue by determo13** [CryptoGnome/Gnome-Feeder#13]
Hi CG, just join trading and started with your youtube video, ‘low balanced settings’ from 11jan, then downloaded fresh settings from git 5h old and notice values dramatically changed from the one on youtube.  Sections downsidevolatility and others gone completely, is that settings on youtube doesn't work anymore?

**Comment by determo13** [comment]
from the youtube:

{
  "General": {
    "BaseCurrency": "BTC", // MARKET
    "BuyStrategy": "EMASPREAD", // ALL_buy_strategy
    "BuyValue": "-0.377", // ALL_buy_value
    "Cost": "0.001", // ALL_max_cost or or All_max_cost_percentage
    "DcaEnabled": "-2", // ALL_DCA_enabled
    "DcaMaxBuySpread": "2", // max_buy_spread in DCA.properties
    "DcaMaxBuyTimes": "5", // max_buy_times in DCA.properties
    "DcaMaxCost": "0", // max_cost in DCA.properties
    "DcaMinBuyBalance": "0", // min_buy_balance in DCA.properties depending on UseMinBuyBalancePercentage in hostsettings.json
    "DcaSellTrigger": "1", // sell_trigger in DCA.properties
    "DcaSellStrategy": "GAIN", // sell_strategy in DCA.properties
    "DcaSellValue": "1", // sell_value in DCA.properties
    "DcaTrailingBuy": "0.277", // trailing_buy in DCA.properties
    "DcaTrailingProfit": "0.277", // trialing_profit in DCA.properties
    "ExcludedPairs": "BNB", // coins you don't want PTF to create settings for. These will have no config generated and will appear in watchmode
    "SomOnlyPairs": "MTL,DGD,TRIG,MTL,SWIFT,ARDR,SAFEX,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME", // these are coins where BASE_COIN_sell_only_mode will be true
    "DcaExcluded": "", // coins you don't want DCA enabled for no matter what
    "MaxBuySpread": ".75", // All_max_buy_spread
    "MaxTrailingBuy": "0.377", // All_trailing_buy
    "MaxTrailingProfit": "0.377", // All_tailing_profit
    "MinBuyBalance": "50", // All_min_buy_balance or All_min_buy_balance_percentage
    "MinBuyPrice": "0.00005", // All_min_buy_price
    "MinBuyVolume": "800", // All_min_buy_volume
    "MinProfit": "1", // All_min_profit
    "MinTrailingBuy": "0.0177", // minumum the trailing buy after offsets can be
    "MinTrailingProfit": "0.0177", // minumum the trailing buy after offsets can be
    "MinutesForLongerTermTrend": "720", // minutes to measure trend for LongerTermPriceChange
    "MinutesToMeasureTrend": "60", // minutes to measure trend for base coin trend, PriceTrendChange and volatility calc
    "NumberOfPairs": "3", // ALL_max_trading_pairs
    "SellStrategy": "GAIN", // ALL_sell_strategy
    "SellValue": ".85", // ALL_sell_value
    "TopCurrenciesToCheck": "50" // number of pairs to check from your exchange for MaxTopCoinAverageChange
  },
  "MarketConditions": {
    "Configs": [
      {
        "FolderName": "01-superbear",
        "MaxTopCoinAverageChange": "-3",
        "MinBaseCoinPriceChange": "2",
        "SellOnlyMode": "true",
        "DcaEnabled": "false",
        "TrailingProfitOffset": "-20",
        "SellValueOffset": "-20"
      },
      {
        "FolderName": "02-bear",
        "MaxTopCoinAverageChange": "-1.5",
        "MinBaseCoinPriceChange": "1",
        "BuyValueOffset": "-30",
        "MinBuyBalanceOffset": "20",
        "MaxPairsOffset": "-20",
        "DcaTrailingBuyOffset":"25",
        "DcaTrailingProfitOffset":"-25",
        "DcaSellValueOffset":"-10",
        "DcaMaxBuySpreadOffset": "20",
        "DcaMaxBuyTimesOffset": "-25",
        "DcaEnabled": "50",
        "SellValueOffset": "-30"
      },
      {
        "FolderName": "03-boring",
        "MaxTopCoinAverageChange": "3",
        "MinBaseCoinPriceChange": "-1"
      },
      {
        "FolderName": "04-bull",
        "MaxTopCoinAverageChange": "5",
        "MinBaseCoinPriceChange": "-2",
        "DcaTrailingBuyOffset":"-10",
        "DcaTrailingProfitOffset":"10",
        "DcaSellValueOffset":"10",
        "BuyValueOffset": "2"
      },
      {
        "FolderName": "05-superbull",
        "MaxTopCoinAverageChange": "1000",
        "MinBaseCoinPriceChange": "-10000",
        "DcaTrailingBuyOffset":"-20",
        "DcaTrailingProfitOffset":"20",
        "DcaSellValueOffset":"20",
        "BuyValueOffset": "5",
        "MinBuyBalanceOffset": "5",
        "MaxPairsOffset": "20"
      }
    ]
  },
  "Volume": {
    "Configs": [
      {
        "MaxVolume": "200",
        "BuyValueOffset": "-20",
        "CostOffset": "-30",
        "TrailingBuyOffset":"20",
        "TrailingProfitOffset":"-30"
      },
      {
        "MaxVolume": "300",
        "BuyValueOffset": "-10",
        "CostOffset": "-20",
        "TrailingBuyOffset":"10",
        "TrailingProfitOffset":"-20"
      },
      {
        "MaxVolume": "500",
        "BuyValueOffset": "-12",
        "TrailingBuyOffset":"10",
        "TrailingProfitOffset":"-20"
      }
    ]
  },
   "PriceTrendChange": {
    "Configs": [

    {
        "MaxPriceTrendPercentageChange": "-5",
        "SellOnlyMode": "true",
        "DcaEnabled": "false",
        "TrailingProfitOffset": "-20",
        "SellValueOffset": "-20"
      },
      {
        "MaxPriceTrendPercentageChange": "-0.3",
        "BuyValueOffset": "-100",
        "CostOffset": "-50",
        "TrailingBuyOffset":"20",
        "TrailingProfitOffset":"-40",
        "SellValueOffset": "-5"
      },
      {
        "MaxPriceTrendPercentageChange": "2.5",
        "BuyValueOffset": "-5",
        "TrailingBuyOffset":"-70",
        "TrailingProfitOffset":"5"
      },
      {
        "MaxPriceTrendPercentageChange": "20",
        "TrailingBuyOffset": "-50",
        "TrailingProfitOffset": "5"
      },
      {
        "MaxPriceTrendPercentageChange": "15000",
        "SellOnlyMode": "true",
        "DcaEnabled": "false",
        "TrailingProfitOffset": "-20",
        "SellValueOffset": "-20"
      }
    ]
  },
  "LongerTermPriceChange": {
    "Configs": [
      {
        "MaxPriceTrendPercentageChange": "-5",
        "SellOnlyMode": "true",
        "TrailingProfitOffset": "-80",
        "SellValueOffset": "-20",
        "DcaEnabled": "false"
      },
      {
        "MaxPriceTrendPercentageChange": "15"
      },
      {
        "MaxPriceTrendPercentageChange": "10000",
        "SellOnlyMode": "true",
        "TrailingProfitOffset": "-100",
        "SellValueOffset": "-20",
        "DcaEnabled": "false"
      }
    ]
  },
  "UpsideVolatility": {
    "Configs": [
      {
        "MaxChangeFromOpen": "0.2",
        "SellOnlyMode": "true",
        "TrailingProfitOffset": "-80",
        "SellValueOffset": "-20",
        "DcaEnabled": "false"
      }
    ]
  },
  "DownsideVolatility": {
    "Configs": [
      {
        "MaxChangeFromOpen": "0.2",
        "SellOnlyMode": "true",
        "TrailingProfitOffset": "-80",
        "SellValueOffset": "-30",
        "DcaEnabled": "false"
      }
    ]
  },
  "AverageCandleSize": {
    "Configs": [
      {
        "MaxPercentageSizeOfPrice": "0.1",
        "SellOnlyMode": "true",
        "TrailingProfitOffset": "-80",
        "SellValueOffset": "-30"
      }
    ]
  }
}

**Comment by rahgulla** [comment]
I have the same question than @determo13

**Comment by CryptoGnome** [comment]
yes I update and you can choose to stay on a old version or update. I try to notate the changes in the version control section
