### ISSUE TITLE
Appsettings max pairs not matching

### ISSUE THREAD

**Issue by PoconoCrypto** [CryptoGnome/Gnome-Feeder#14]
In my feeder appsettings I have it set for 8 but it keeps generating the pairs to use 12. I did restart feeder with same results.

**Comment by russweir** [comment]
@PoconoCrypto hey mate, just checking if you have taken into account the offset changes in market conditions? these settings will change your mMax pairs based on the market i.e Boring will increase your number by 75% i think from memory

**Comment by PoconoCrypto** [comment]
Ah that would make sense, then I was going nuts trying to figure out where it is coming from
