### ISSUE TITLE
Jar File on PT

### ISSUE THREAD

**Issue by BitBrush64** [CryptoGnome/Gnome-Feeder#4]
Installed PT and trying to run the default settings on my Windows 10 machine. Added in my exchange and API keys. That's it. When I try to run PT, I keep getting the following error in the command prompt: 

C:\WINDOWS\system32>java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx512m -Xms512m
Error: Unable to access jarfile ProfitTrailer.jar.

Can anyone tell me how to fix that?? I am not a coder, but I have spent hours trying to figure it out by searching for help on Telegram and Discord. Please help so I can at least turn this thing on!! Thank you!

**Comment by sil3ntcor3** [comment]
You need to run the command from the same location as the ProfitTrailer.jar file.
