### ISSUE TITLE
PTF not buy for day

### ISSUE THREAD

**Issue by mosvision** [CryptoGnome/Gnome-Feeder#6]
I have not buy with that settings for a day. That is normal?

**Comment by woodyalien** [comment]
I would say yes, expected
I do not use gnome's but I have only 5% of my usual trades today as the market is very undefined

**Comment by nmalancea** [comment]
@mosvision make sure the bot isn't frozen. Prices of your pairs should change every 10 seconds or so. It was frozen for me even though it has a heartbeat.
